@UrlShortner_HostAddress = https://localhost:7095


POST {{UrlShortner_HostAddress}}/generate
Content-Type: application/json
Accept: application/json

{
  "originalUrl": "https://github.com/"
}

###
GET {{UrlShortner_HostAddress}}/{shortUrl}
Accept: application/json

